language: objective-c
osx_image: xcode7
xcode_project: Example/MLLayoutDemo.xcworkspace
xcode_scheme: MLLayoutDemo
before_install:
- brew update
- brew upgrade xctool
script:
- xctool -workspace Example/MLLayoutDemo.xcworkspace -scheme MLLayoutDemo build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool -workspace Example/MLLayoutDemo.xcworkspace -scheme MLLayoutDemo test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

